from typing import Any

from aws_cdk import (
    Acknowledgment,
    CfnOutput,
    Duration,
    RemovalPolicy,
    Stack,
    Tags,
    Validations,
)
from aws_cdk import (
    aws_bedrock as bedrock,
)
from aws_cdk import (
    aws_ecr as ecr,
)
from aws_cdk import (
    aws_iam as iam,
)
from aws_cdk import (
    aws_lambda as lambda_,
)
from aws_cdk import (
    aws_logs as logs,
)
from aws_cdk import (
    aws_s3 as s3,
)
from aws_cdk import (
    aws_s3vectors as s3vectors,
)
from constructs import Construct

# cohere, because ap-southeast-1 has no titan embedding model at all. 1024 dimensions is what
# the index is built for and changing it means a new index and a full re-ingest
EMBEDDING_MODEL = "cohere.embed-english-v3"
ANSWER_MODEL = "anthropic.claude-haiku-4-5-20251001-v1:0"
EMBEDDING_DIMENSION = 1024
# bedrock stores its own text and metadata against every vector, and both count against the
# filterable metadata budget unless they are declared unfilterable
BEDROCK_RESERVED = ["AMAZON_BEDROCK_METADATA", "AMAZON_BEDROCK_TEXT"]

CORPUS_WILDCARD = (
    "The knowledge base role reads every object under docs/ because the corpus is a few "
    "thousand files whose names are generated from wikipedia titles and regulation issue "
    "dates. The grant is scoped to that one prefix of one bucket and carries no write action."
)

VECTOR_WILDCARD = (
    "The knowledge base role writes vectors into the one index this stack creates. S3 Vectors "
    "authorises index operations on the index arn, and the sub-resource paths beneath it are "
    "not enumerable at synth time."
)

GRANT_ACTIONS = (
    "The S3 action families come from the CDK grant helpers, which expand read and write into "
    "s3:GetObject*, s3:List*, s3:Abort* and s3:DeleteObject*. Every one is bound to a single "
    "bucket arn written out below."
)

LAKE_OBJECTS = (
    "The functions read the lake by key. Views, marts and the fastf1 cache are all addressed by "
    "generated keys, so an object-level allowlist would be rewritten on every ingest. The grant "
    "is read-only and scoped to the one bucket."
)

ATHENA_RESULTS = (
    "Athena writes each query's result set to a key it chooses inside the results bucket, so the "
    "caller has to be able to read and delete anything in it. That bucket holds nothing but "
    "query output and expires on a lifecycle rule."
)

CATALOG_WILDCARD = (
    "Reading a table through Athena needs glue:GetTable on the table arn, and the mart names are "
    "generated by dbt. The grant is scoped to this environment's database."
)

SIM_VERSIONS = (
    "Invoking the simulation function matches its published versions and aliases, which is what "
    "the trailing :* covers. It is one function arn."
)

RUNTIME_MANAGED = (
    "The two functions use the AWS-managed basic execution policy for CloudWatch Logs. Every "
    "other permission they hold is written out here and scoped to a resource."
)

NO_DLQ = (
    "No dead-letter queue. Both functions are synchronous: the ask function answers a caller "
    "that is waiting for the reply, and the simulation function is invoked by it. A failed "
    "invocation has a caller to return the error to, so there is nothing a queue would catch "
    "that the response does not. Accepted risk."
)

NO_VPC = (
    "Neither function runs in a VPC. Both need egress to Bedrock, Athena and S3, and a "
    "VPC-attached function reaching those needs either a NAT gateway or four interface "
    "endpoints, which are the two largest line items this budget refuses. The functions hold "
    "no inbound network surface and their IAM is scoped per resource. Accepted risk."
)

# narrow on purpose: it is about the reader's money, not about probabilities. an earlier and
# broader wording classified "who is favourite and with what win probability" as betting and
# blocked the question this system exists to answer
GUARDRAIL_TOPIC = (
    "Recommending or sizing a wager: how much to stake, bankroll management, which bet is "
    "value, or supplying bookmaker odds. Not forecast probabilities or who a model favours."
)


class AgentStack(Stack):
    def __init__(
        self,
        scope: Construct,
        construct_id: str,
        *,
        env_name: str,
        **kwargs: Any,
    ) -> None:
        super().__init__(scope, construct_id, **kwargs)
        Tags.of(self).add("component", "agent")

        bucket_name = (
            self.node.try_get_context("dataBucket") or f"pit-advisor-data-{env_name}-{self.account}"
        )
        database_name = f"pitadvisor_{env_name}"
        workgroup_name = self.node.try_get_context("athenaWorkgroup") or "pitadvisor"
        image_tag = self.node.try_get_context("pipelineImageTag") or "latest"

        self.lake_name = bucket_name
        self.database_name = database_name
        lake = s3.Bucket.from_bucket_name(self, "Lake", bucket_name)
        repository = ecr.Repository.from_repository_name(
            self, "PipelineImage", f"pitadvisor-pipeline-{env_name}"
        )

        self.vector_bucket = s3vectors.CfnVectorBucket(
            self,
            "VectorBucket",
            vector_bucket_name=f"pit-advisor-vectors-{env_name}-{self.account}",
        )
        self.index = s3vectors.CfnIndex(
            self,
            "CorpusIndex",
            index_name=f"pitadvisor-corpus-{env_name}",
            # ref on a vector bucket is its arn, not its name, and the name field caps at 63
            vector_bucket_arn=self.vector_bucket.attr_vector_bucket_arn,
            data_type="float32",
            dimension=EMBEDDING_DIMENSION,
            distance_metric="cosine",
            metadata_configuration=s3vectors.CfnIndex.MetadataConfigurationProperty(
                non_filterable_metadata_keys=BEDROCK_RESERVED
            ),
        )
        self.index.add_dependency(self.vector_bucket)

        embedding_arn = f"arn:aws:bedrock:{self.region}::foundation-model/{EMBEDDING_MODEL}"
        self.knowledge_role = knowledge_role = iam.Role(
            self,
            "KnowledgeBaseRole",
            role_name=f"pitadvisor-kb-{env_name}",
            assumed_by=iam.ServicePrincipal(
                "bedrock.amazonaws.com",
                conditions={
                    "StringEquals": {"aws:SourceAccount": self.account},
                    "ArnLike": {
                        "aws:SourceArn": f"arn:aws:bedrock:{self.region}:"
                        f"{self.account}:knowledge-base/*"
                    },
                },
            ),
        )
        knowledge_role.add_to_policy(
            iam.PolicyStatement(actions=["bedrock:InvokeModel"], resources=[embedding_arn])
        )
        knowledge_role.add_managed_policy(
            iam.ManagedPolicy.from_managed_policy_name(
                self, "CorpusReadAccess", f"pitadvisor-kb-corpus-{env_name}"
            )
        )
        knowledge_role.add_to_policy(
            iam.PolicyStatement(
                actions=[
                    "s3vectors:GetIndex",
                    "s3vectors:PutVectors",
                    "s3vectors:GetVectors",
                    "s3vectors:QueryVectors",
                    "s3vectors:ListVectors",
                    "s3vectors:DeleteVectors",
                ],
                resources=[self.index.attr_index_arn, f"{self.index.attr_index_arn}/*"],
            )
        )

        self.knowledge_base = bedrock.CfnKnowledgeBase(
            self,
            "Corpus",
            name=f"pitadvisor-corpus-{env_name}",
            description="Regulations, event documents and the race write-ups jolpica links to.",
            role_arn=knowledge_role.role_arn,
            knowledge_base_configuration=bedrock.CfnKnowledgeBase.KnowledgeBaseConfigurationProperty(
                type="VECTOR",
                vector_knowledge_base_configuration=(
                    bedrock.CfnKnowledgeBase.VectorKnowledgeBaseConfigurationProperty(
                        embedding_model_arn=embedding_arn
                    )
                ),
            ),
            storage_configuration=bedrock.CfnKnowledgeBase.StorageConfigurationProperty(
                type="S3_VECTORS",
                s3_vectors_configuration=(
                    bedrock.CfnKnowledgeBase.S3VectorsConfigurationProperty(
                        index_arn=self.index.attr_index_arn,
                        vector_bucket_arn=self.vector_bucket.attr_vector_bucket_arn,
                    )
                ),
            ),
        )
        self.knowledge_base.node.add_dependency(knowledge_role)

        self.data_source = bedrock.CfnDataSource(
            self,
            "CorpusDocs",
            name=f"pitadvisor-docs-{env_name}",
            knowledge_base_id=self.knowledge_base.attr_knowledge_base_id,
            # the documents are rebuildable from raw/, so deleting the source should take the
            # vectors with it rather than leaving an index nothing points at
            data_deletion_policy="DELETE",
            data_source_configuration=bedrock.CfnDataSource.DataSourceConfigurationProperty(
                type="S3",
                s3_configuration=bedrock.CfnDataSource.S3DataSourceConfigurationProperty(
                    bucket_arn=lake.bucket_arn, inclusion_prefixes=["docs/"]
                ),
            ),
            vector_ingestion_configuration=(
                bedrock.CfnDataSource.VectorIngestionConfigurationProperty(
                    chunking_configuration=bedrock.CfnDataSource.ChunkingConfigurationProperty(
                        chunking_strategy="FIXED_SIZE",
                        fixed_size_chunking_configuration=(
                            bedrock.CfnDataSource.FixedSizeChunkingConfigurationProperty(
                                max_tokens=300, overlap_percentage=20
                            )
                        ),
                    )
                )
            ),
        )

        self.guardrail = bedrock.CfnGuardrail(
            self,
            "Guardrail",
            name=f"pitadvisor-{env_name}",
            description="Denies staking advice and checks that answers stay on the sources.",
            blocked_input_messaging="This system forecasts races. It does not advise on betting.",
            blocked_outputs_messaging="Withheld: that is not something this system answers.",
            topic_policy_config=bedrock.CfnGuardrail.TopicPolicyConfigProperty(
                topics_config=[
                    bedrock.CfnGuardrail.TopicConfigProperty(
                        name="StakingAdvice",
                        definition=GUARDRAIL_TOPIC,
                        type="DENY",
                        examples=[
                            "How much should I put on the favourite?",
                            "What are the best bookmaker odds for this race?",
                            "Give me a betting tip for the grand prix.",
                            "Is there value backing Norris each way?",
                        ],
                    )
                ]
            ),
        )

        self.sim_function = self._function(
            "RaceSim",
            f"pitadvisor-race-sim-{env_name}",
            repository,
            image_tag,
            "pitadvisor.handlers.race_sim.handler",
            env_name,
            bucket_name,
            memory=3008,
            timeout=Duration.minutes(2),
        )
        self.ask_function = self._function(
            "Ask",
            f"pitadvisor-ask-{env_name}",
            repository,
            image_tag,
            "pitadvisor.handlers.ask.handler",
            env_name,
            bucket_name,
            memory=2048,
            timeout=Duration.minutes(1),
            extra_environment={
                "PITADV_KNOWLEDGE_BASE_ID": self.knowledge_base.attr_knowledge_base_id,
                "PITADV_GUARDRAIL_ID": self.guardrail.attr_guardrail_id,
                "PITADV_GUARDRAIL_VERSION": "DRAFT",
            },
        )

        lake_access = iam.ManagedPolicy.from_managed_policy_name(
            self, "AgentLakeAccess", f"pitadvisor-agent-lake-{env_name}"
        )
        for function in (self.sim_function, self.ask_function):
            function.role.add_managed_policy(lake_access)  # type: ignore[union-attr]

        for statement in self._global_inference_statements():
            self.ask_function.add_to_role_policy(statement)
        self.ask_function.add_to_role_policy(
            iam.PolicyStatement(
                actions=["bedrock:ApplyGuardrail"],
                resources=[self.guardrail.attr_guardrail_arn],
            )
        )
        self.ask_function.add_to_role_policy(
            iam.PolicyStatement(
                actions=["bedrock:Retrieve"],
                resources=[self.knowledge_base.attr_knowledge_base_arn],
            )
        )
        self.ask_function.add_to_role_policy(
            iam.PolicyStatement(
                actions=[
                    "athena:StartQueryExecution",
                    "athena:GetQueryExecution",
                    "athena:GetQueryResults",
                ],
                resources=[
                    f"arn:aws:athena:{self.region}:{self.account}:workgroup/{workgroup_name}"
                ],
            )
        )
        self.ask_function.add_to_role_policy(
            iam.PolicyStatement(
                actions=[
                    "glue:GetTable",
                    "glue:GetTables",
                    "glue:GetDatabase",
                    "glue:GetPartitions",
                ],
                resources=[
                    f"arn:aws:glue:{self.region}:{self.account}:catalog",
                    f"arn:aws:glue:{self.region}:{self.account}:database/{database_name}",
                    f"arn:aws:glue:{self.region}:{self.account}:table/{database_name}/*",
                ],
            )
        )
        self.ask_function.add_to_role_policy(
            iam.PolicyStatement(
                actions=["lambda:InvokeFunction"],
                resources=[self.sim_function.function_arn],
            )
        )

        # IAM auth, not public: an open url in front of a function that spends bedrock tokens
        # is a bill someone else can run up
        self.url = self.ask_function.add_function_url(auth_type=lambda_.FunctionUrlAuthType.AWS_IAM)

        dev_user = iam.User.from_user_name(
            self,
            "DevUser",
            self.node.try_get_context("devUserName") or "pitadvisor-dev",
        )
        self.dev_access = iam.ManagedPolicy(
            self,
            "DevAgentAccess",
            managed_policy_name=f"pitadvisor-agent-access-{env_name}",
            users=[dev_user],
            statements=[
                *self._global_inference_statements(),
                iam.PolicyStatement(
                    actions=["bedrock:Retrieve", "bedrock:ListKnowledgeBases"],
                    resources=[self.knowledge_base.attr_knowledge_base_arn],
                ),
                iam.PolicyStatement(
                    actions=["bedrock:StartIngestionJob", "bedrock:GetIngestionJob"],
                    resources=[self.knowledge_base.attr_knowledge_base_arn],
                ),
                iam.PolicyStatement(
                    actions=["bedrock:ApplyGuardrail", "bedrock:GetGuardrail"],
                    resources=[self.guardrail.attr_guardrail_arn],
                ),
            ],
        )

        self._acknowledge()

        CfnOutput(self, "KnowledgeBaseId", value=self.knowledge_base.attr_knowledge_base_id)
        CfnOutput(self, "DataSourceId", value=self.data_source.attr_data_source_id)
        CfnOutput(self, "GuardrailId", value=self.guardrail.attr_guardrail_id)
        CfnOutput(self, "AskFunctionUrl", value=self.url.url)
        CfnOutput(self, "VectorIndexArn", value=self.index.attr_index_arn)

    def _function(
        self,
        construct_id: str,
        name: str,
        repository: ecr.IRepository,
        image_tag: str,
        entry: str,
        env_name: str,
        bucket_name: str,
        memory: int,
        timeout: Duration,
        extra_environment: dict[str, str] | None = None,
    ) -> lambda_.DockerImageFunction:
        environment = {
            "PITADV_ENV": env_name,
            "PITADV_DATA_BUCKET": bucket_name,
            # there is no ~/.aws in the image, so a named profile is a ProfileNotFound
            "PITADV_AWS_PROFILE": "",
            "POWERTOOLS_SERVICE_NAME": name,
            "POWERTOOLS_LOG_LEVEL": "INFO",
            **(extra_environment or {}),
        }
        log_group = logs.LogGroup(
            self,
            f"{construct_id}Logs",
            log_group_name=f"/aws/lambda/{name}",
            retention=logs.RetentionDays.TWO_WEEKS,
            removal_policy=RemovalPolicy.DESTROY,
        )
        # an explicit role rather than the managed basic-execution policy: the only logging
        # this function does goes to the group above, so that is the only grant it needs
        role = iam.Role(
            self,
            f"{construct_id}Role",
            role_name=f"{name}-role",
            assumed_by=iam.ServicePrincipal("lambda.amazonaws.com"),
            inline_policies={
                "Logs": iam.PolicyDocument(
                    statements=[
                        iam.PolicyStatement(
                            actions=["logs:CreateLogStream", "logs:PutLogEvents"],
                            resources=[log_group.log_group_arn],
                        )
                    ]
                )
            },
        )
        return lambda_.DockerImageFunction(
            self,
            construct_id,
            function_name=name,
            code=lambda_.DockerImageCode.from_ecr(
                repository,
                tag_or_digest=image_tag,
                # the image has no lambda entrypoint of its own, the pipeline steps pass their
                # own command, so the runtime interface client is named here
                entrypoint=["/opt/venv/bin/python", "-m", "awslambdaric"],
                cmd=[entry],
            ),
            architecture=lambda_.Architecture.ARM_64,
            memory_size=memory,
            timeout=timeout,
            environment=environment,
            role=role,
            log_group=log_group,
        )

    def _global_inference_statements(self) -> list[iam.PolicyStatement]:
        """The three-part grant the global cross-region inference docs specify. Nothing here
        carries a wildcard: a global profile resolves the model in the calling region and again
        at the global scope, and each step is conditioned on the profile it came through."""
        profile = (
            f"arn:aws:bedrock:{self.region}:{self.account}:inference-profile/global.{ANSWER_MODEL}"
        )
        return [
            iam.PolicyStatement(
                actions=["bedrock:InvokeModel", "bedrock:InvokeModelWithResponseStream"],
                resources=[profile],
                conditions={"StringEquals": {"aws:RequestedRegion": self.region}},
            ),
            iam.PolicyStatement(
                actions=["bedrock:InvokeModel", "bedrock:InvokeModelWithResponseStream"],
                resources=[f"arn:aws:bedrock:{self.region}::foundation-model/{ANSWER_MODEL}"],
                conditions={
                    "StringEquals": {
                        "aws:RequestedRegion": self.region,
                        "bedrock:InferenceProfileArn": profile,
                    }
                },
            ),
            iam.PolicyStatement(
                actions=["bedrock:InvokeModel", "bedrock:InvokeModelWithResponseStream"],
                resources=[f"arn:aws:bedrock:::foundation-model/{ANSWER_MODEL}"],
                conditions={
                    "StringEquals": {
                        "aws:RequestedRegion": "unspecified",
                        "bedrock:InferenceProfileArn": profile,
                    }
                },
            ),
        ]

    def _acknowledge(self) -> None:
        Validations.of(self.knowledge_role).acknowledge(
            Acknowledgment(
                id="AwsSolutions-IAM5[Resource::<CorpusIndex.IndexArn>/*]",
                reason=VECTOR_WILDCARD,
            ),
            Acknowledgment(
                id=(
                    "AwsSolutions-IAM5[Resource::arn:aws:glue:"
                    f"{self.region}:{self.account}:table/{self.database_name}/*]"
                ),
                reason=CATALOG_WILDCARD,
            ),
        )
