from typing import Any

from aws_cdk import (
    Acknowledgment,
    CfnOutput,
    Duration,
    RemovalPolicy,
    Stack,
    Tags,
    Validations,
)
from aws_cdk import (
    aws_ec2 as ec2,
)
from aws_cdk import (
    aws_ecr as ecr,
)
from aws_cdk import (
    aws_ecs as ecs,
)
from aws_cdk import (
    aws_events as events,
)
from aws_cdk import (
    aws_events_targets as targets,
)
from aws_cdk import (
    aws_iam as iam,
)
from aws_cdk import (
    aws_logs as logs,
)
from aws_cdk import (
    aws_stepfunctions as sfn,
)
from constructs import Construct

CATALOG_WILDCARD = (
    "dbt creates and drops silver and gold tables on every build, so the table grant cannot be "
    "enumerated. It is scoped to the pitadvisor database and to that database only. The lake "
    "grants this role also carries are written in the data stack, next to the bucket."
)

STATE_MACHINE_WILDCARD = (
    "The state machine's own policy is generated by the EcsRunTask integration: it needs "
    "ecs:RunTask on every revision of the one task definition, and the events rule that "
    "watches the task it started. Both are scoped to that task definition."
)

NO_FLOW_LOGS = (
    "VPC flow logs are off. The only thing in this VPC is a short-lived Fargate task with a "
    "public IP talking to S3, Glue and two public APIs, and flow logs would cost more per month "
    "than the tasks themselves inside a $20 cap. Accepted risk."
)

NO_CONTAINER_INSIGHTS = (
    "Container Insights is off. It bills per metric on a cluster that runs a handful of tasks a "
    "week, and the task already ships structured logs to CloudWatch with the run id. "
    "Accepted risk."
)

PLAIN_ENVIRONMENT = (
    "The task environment holds the bucket name, the region and the season being processed. "
    "There is no secret in it: the pipeline authenticates with its task role."
)

PUBLIC_SUBNET = (
    "The task runs in a public subnet with a public IP and no inbound rules. The alternative "
    "is a NAT Gateway at roughly $32/month, which is more than the whole budget for everything "
    "else. Egress-only, short-lived, no listener. Accepted risk."
)


class TransformStack(Stack):
    def __init__(
        self,
        scope: Construct,
        construct_id: str,
        *,
        env_name: str,
        **kwargs: Any,
    ) -> None:
        super().__init__(scope, construct_id, **kwargs)
        Tags.of(self).add("component", "transform")

        bucket_name = (
            self.node.try_get_context("dataBucket") or f"pit-advisor-data-{env_name}-{self.account}"
        )
        results_bucket_name = f"pit-advisor-athena-results-{env_name}-{self.account}"
        database_name = f"pitadvisor_{env_name}"
        workgroup_name = self.node.try_get_context("athenaWorkgroup") or "pitadvisor"
        ledger_table = f"pitadvisor-ingest-{env_name}"
        image_tag = self.node.try_get_context("pipelineImageTag") or "latest"

        self.repository = ecr.Repository(
            self,
            "PipelineImage",
            repository_name=f"pitadvisor-pipeline-{env_name}",
            image_scan_on_push=True,
            encryption=ecr.RepositoryEncryption.AES_256,
            removal_policy=RemovalPolicy.DESTROY,
            empty_on_delete=True,
            lifecycle_rules=[ecr.LifecycleRule(max_image_count=5)],
        )

        # public subnets only: a NAT gateway costs more than the rest of this project together
        self.vpc = ec2.Vpc(
            self,
            "PipelineVpc",
            max_azs=2,
            nat_gateways=0,
            subnet_configuration=[
                ec2.SubnetConfiguration(
                    name="public", subnet_type=ec2.SubnetType.PUBLIC, cidr_mask=24
                )
            ],
        )
        Validations.of(self.vpc).acknowledge(
            Acknowledgment(id="AwsSolutions-VPC7", reason=NO_FLOW_LOGS)
        )

        self.cluster = ecs.Cluster(
            self,
            "PipelineCluster",
            cluster_name=f"pitadvisor-{env_name}",
            vpc=self.vpc,
            container_insights_v2=ecs.ContainerInsights.DISABLED,
        )
        Validations.of(self.cluster).acknowledge(
            Acknowledgment(id="AwsSolutions-ECS4", reason=NO_CONTAINER_INSIGHTS)
        )

        self.log_group = logs.LogGroup(
            self,
            "PipelineLogs",
            log_group_name=f"/pitadvisor/{env_name}/pipeline",
            retention=logs.RetentionDays.TWO_WEEKS,
            removal_policy=RemovalPolicy.DESTROY,
        )

        self.task_role = iam.Role(
            self,
            "PipelineTaskRole",
            assumed_by=iam.ServicePrincipal("ecs-tasks.amazonaws.com"),
            description="what the ingest, dbt and view steps are allowed to touch",
            managed_policies=[
                iam.ManagedPolicy.from_managed_policy_name(
                    self, "LakeAccess", f"pitadvisor-pipeline-lake-{env_name}"
                )
            ],
        )
        self.task_role.add_to_policy(
            iam.PolicyStatement(
                actions=[
                    "athena:StartQueryExecution",
                    "athena:GetQueryExecution",
                    "athena:GetQueryResults",
                    "athena:GetWorkGroup",
                    "athena:StopQueryExecution",
                ],
                resources=[
                    f"arn:aws:athena:{self.region}:{self.account}:workgroup/{workgroup_name}"
                ],
            )
        )
        self.task_role.add_to_policy(
            iam.PolicyStatement(
                actions=[
                    "glue:GetDatabase",
                    "glue:GetDatabases",
                    "glue:GetTable",
                    "glue:GetTables",
                    "glue:GetPartition",
                    "glue:GetPartitions",
                    "glue:CreateTable",
                    "glue:UpdateTable",
                    "glue:DeleteTable",
                    "glue:GetTableVersion",
                    "glue:GetTableVersions",
                    "glue:DeleteTableVersion",
                    "glue:BatchDeleteTableVersion",
                    "glue:BatchCreatePartition",
                    "glue:BatchDeletePartition",
                ],
                resources=[
                    # literal partition: an acknowledgment id cannot hold what ${AWS::Partition}
                    # renders to
                    f"arn:aws:glue:{self.region}:{self.account}:catalog",
                    f"arn:aws:glue:{self.region}:{self.account}:database/{database_name}",
                    f"arn:aws:glue:{self.region}:{self.account}:table/{database_name}/*",
                ],
            )
        )
        self.task_role.add_to_policy(
            iam.PolicyStatement(
                actions=[
                    "dynamodb:GetItem",
                    "dynamodb:PutItem",
                    "dynamodb:UpdateItem",
                    "dynamodb:Query",
                ],
                resources=[f"arn:aws:dynamodb:{self.region}:{self.account}:table/{ledger_table}"],
            )
        )
        # the granular finding id would carry an s3 arn, whose ::: is not a legal
        # acknowledgment id, so the whole rule is acknowledged on the generated policy
        Validations.of(self.task_role).acknowledge(
            Acknowledgment(
                id=(
                    "AwsSolutions-IAM5[Resource::arn:aws:glue:"
                    f"{self.region}:{self.account}:table/{database_name}/*]"
                ),
                reason=CATALOG_WILDCARD,
            )
        )

        self.security_group = ec2.SecurityGroup(
            self,
            "PipelineSecurityGroup",
            vpc=self.vpc,
            description="egress only, the pipeline task listens for nothing",
            allow_all_outbound=True,
        )

        self.family = f"pitadvisor-pipeline-{env_name}"
        self.task_definition = ecs.FargateTaskDefinition(
            self,
            "PipelineTask",
            family=self.family,
            cpu=512,
            memory_limit_mib=1024,
            runtime_platform=ecs.RuntimePlatform(
                cpu_architecture=ecs.CpuArchitecture.ARM64,
                operating_system_family=ecs.OperatingSystemFamily.LINUX,
            ),
            task_role=self.task_role,
        )
        self.container = self.task_definition.add_container(
            "pipeline",
            image=ecs.ContainerImage.from_ecr_repository(self.repository, image_tag),
            logging=ecs.LogDrivers.aws_logs(stream_prefix="pipeline", log_group=self.log_group),
            environment={
                "PITADV_ENV": env_name,
                "PITADV_DATA_BUCKET": bucket_name,
                "PITADV_GLUE_DATABASE": database_name,
                "PITADV_ATHENA_WORKGROUP": workgroup_name,
                "PITADV_LEDGER_TABLE": ledger_table,
                # ephemeral disk, the lake keeps the warm copy under cache/fastf1/
                "PITADV_FASTF1_CACHE": "/tmp/fastf1",
                "PITADV_AWS_REGION": self.region,
                # the container has a task role, there is no profile to resolve
                "PITADV_AWS_PROFILE": "",
                "PITADV_ATHENA_STAGING": f"s3://{results_bucket_name}/athena/",
                "PITADV_SILVER_DIR": f"s3://{bucket_name}/silver/",
                "PITADV_GOLD_DIR": f"s3://{bucket_name}/gold/",
            },
        )
        Validations.of(self.task_definition).acknowledge(
            Acknowledgment(id="AwsSolutions-ECS2", reason=PLAIN_ENVIRONMENT)
        )

        definition = (
            self._step("IngestJolpica", "pitadv ingest --source jolpica --season $SEASON")
            .next(self._step("IngestWeather", "pitadv ingest --source open_meteo --season $SEASON"))
            .next(
                self._step(
                    "IngestSession",
                    "pitadv ingest --source fastf1 --season $SEASON --round $ROUND --session race",
                )
            )
            .next(self._quality_gate())
            .next(self._step("SyncCatalog", "pitadv catalog-sync"))
            .next(
                self._step(
                    "DbtBuild", "dbt build --project-dir transform --target athena --fail-fast"
                )
            )
            .next(self._step("CheckLineage", "pitadv lineage --check"))
            .next(self._step("EmitViews", "pitadv emit-views"))
        )

        self.state_machine = sfn.StateMachine(
            self,
            "WeekendPipeline",
            state_machine_name=f"pitadvisor-weekend-{env_name}",
            definition_body=sfn.DefinitionBody.from_chainable(definition),
            role=self._pipeline_role(env_name),
            timeout=Duration.hours(2),
            tracing_enabled=True,
            logs=sfn.LogOptions(
                destination=logs.LogGroup(
                    self,
                    "PipelineStateLogs",
                    log_group_name=f"/pitadvisor/{env_name}/weekend-pipeline",
                    retention=logs.RetentionDays.ONE_MONTH,
                    removal_policy=RemovalPolicy.DESTROY,
                ),
                level=sfn.LogLevel.ALL,
            ),
        )

        # off unless asked for: every run costs fargate minutes and jolpica quota
        self.schedule = events.Rule(
            self,
            "MondaySchedule",
            rule_name=f"pitadvisor-weekend-{env_name}",
            description="runs the weekend pipeline the morning after a race",
            schedule=events.Schedule.cron(minute="0", hour="6", week_day="MON"),
            enabled=bool(self.node.try_get_context("enableSchedule")),
            targets=[
                targets.SfnStateMachine(
                    self.state_machine,
                    input=events.RuleTargetInput.from_object({"season": 2025, "round": 1}),
                )
            ],
        )

        Validations.of(self.state_machine.role).acknowledge(
            Acknowledgment(
                id=(
                    "AwsSolutions-IAM5[Resource::arn:aws:ecs:"
                    f"{self.region}:{self.account}:task-definition/{self.family}:*]"
                ),
                reason=STATE_MACHINE_WILDCARD,
            ),
            Acknowledgment(
                id=(
                    "AwsSolutions-IAM5[Resource::arn:aws:ecs:"
                    f"{self.region}:{self.account}:task/pitadvisor-{env_name}/*]"
                ),
                reason=STATE_MACHINE_WILDCARD,
            ),
        )

        CfnOutput(self, "PipelineRepositoryUri", value=self.repository.repository_uri)
        CfnOutput(self, "WeekendPipelineArn", value=self.state_machine.state_machine_arn)

    def _run(self, task_id: str, command: str) -> sfn.CustomState:
        return sfn.CustomState(
            self,
            task_id,
            state_json={
                "Type": "Task",
                "Resource": "arn:aws:states:::ecs:runTask.sync",
                "Parameters": {
                    "Cluster": self.cluster.cluster_arn,
                    "TaskDefinition": self.task_definition.task_definition_arn,
                    "LaunchType": "FARGATE",
                    "NetworkConfiguration": {
                        "AwsvpcConfiguration": {
                            "Subnets": self.vpc.select_subnets(
                                subnet_type=ec2.SubnetType.PUBLIC
                            ).subnet_ids,
                            "SecurityGroups": [self.security_group.security_group_id],
                            "AssignPublicIp": "ENABLED",
                        }
                    },
                    "Overrides": {
                        "ContainerOverrides": [
                            {
                                "Name": self.container.container_name,
                                "Command": ["sh", "-c", command],
                                "Environment": [
                                    # ecs wants strings, the execution input carries numbers
                                    {"Name": "SEASON", "Value.$": "States.Format('{}', $.season)"},
                                    {"Name": "ROUND", "Value.$": "States.Format('{}', $.round)"},
                                    {"Name": "PITADV_RUN_ID", "Value.$": "$$.Execution.Name"},
                                ],
                            }
                        ]
                    },
                },
                "Retry": [
                    {
                        # a retry re-enters the ingest, the request ledger is what stops it
                        # spending the hour's quota twice
                        "ErrorEquals": ["States.TaskFailed", "States.Timeout"],
                        "IntervalSeconds": 30,
                        "MaxAttempts": 2,
                        "BackoffRate": 2,
                    }
                ],
                # the task's own output would replace the season and round the next step reads
                "ResultPath": None,
                "TimeoutSeconds": 1800,
            },
        )

    def _step(self, task_id: str, command: str) -> sfn.CustomState:
        return self._run(task_id, command)

    def _quality_gate(self) -> sfn.Chain:
        halt = sfn.Fail(
            self,
            "QuarantineHalt",
            error="QualityGateFailed",
            cause="bronze failed a contract, freshness or referential check",
        )
        gate = self._run("QualityGate", "pitadv quality-report --layer bronze")
        gate.add_catch(halt, errors=["States.ALL"])
        return sfn.Chain.start(gate)

    def _pipeline_role(self, env_name: str) -> iam.Role:
        role = iam.Role(
            self,
            "PipelineStateRole",
            assumed_by=iam.ServicePrincipal("states.amazonaws.com"),
            description="runs the weekend pipeline's fargate steps and nothing else",
        )
        # literal arns: an acknowledgment id cannot contain the :: that a pseudo parameter renders
        role.add_to_policy(
            iam.PolicyStatement(
                actions=["ecs:RunTask"],
                resources=[
                    f"arn:aws:ecs:{self.region}:{self.account}:task-definition/{self.family}:*"
                ],
            )
        )
        role.add_to_policy(
            iam.PolicyStatement(
                actions=["ecs:StopTask", "ecs:DescribeTasks"],
                resources=[
                    f"arn:aws:ecs:{self.region}:{self.account}:task/pitadvisor-{env_name}/*"
                ],
            )
        )
        role.add_to_policy(
            iam.PolicyStatement(
                actions=["iam:PassRole"],
                resources=[
                    self.task_role.role_arn,
                    self.task_definition.execution_role.role_arn
                    if self.task_definition.execution_role
                    else self.task_role.role_arn,
                ],
            )
        )
        role.add_to_policy(
            iam.PolicyStatement(
                actions=["events:PutTargets", "events:PutRule", "events:DescribeRule"],
                resources=[
                    f"arn:aws:events:{self.region}:{self.account}:rule/"
                    "StepFunctionsGetEventsForECSTaskRule"
                ],
            )
        )
        return role
