from typing import Any

from aws_cdk import (
    Acknowledgment,
    CfnOutput,
    Duration,
    RemovalPolicy,
    Stack,
    Tags,
    Validations,
)
from aws_cdk import (
    aws_cloudfront as cloudfront,
)
from aws_cdk import (
    aws_cloudfront_origins as origins,
)
from aws_cdk import (
    aws_iam as iam,
)
from aws_cdk import (
    aws_s3 as s3,
)
from constructs import Construct

NO_ACCESS_LOGS = (
    "Access logging is off on both the bucket and the distribution. This is a single-user "
    "dashboard serving a few hundred kilobytes of public view artifacts; a request log would be "
    "a larger and faster-growing dataset than the site itself inside a $20/month cap. The "
    "CloudTrail management trail still covers the control plane. Accepted risk."
)

NO_WAF = (
    "No WAF in front of the distribution. The origin is a private bucket of static JSON and "
    "HTML with no form, no API and no state to corrupt, so the only exposure is bandwidth, "
    "which the free tier and the budget alarm already bound. A WAF web ACL would cost more per "
    "month than everything else in this stack combined. Accepted risk."
)

PLACEHOLDER_REPO = "OWNER/REPO"

CI_WILDCARD = (
    "The publish role writes every object in the site bucket, because the export's filenames "
    "are generated by the framework and change on every build. Its only other reach into the "
    "account is a read-only managed policy over the lake's views/ prefix. The role holds no "
    "static credential and is assumable only by this repository's main branch."
)

SITE_WILDCARD = (
    "The publish grant covers every object in the site bucket. The bucket holds nothing but the "
    "output of `pnpm build`, whose filenames are generated by the framework and change on every "
    "build, so an object-level allowlist would be rewritten each time. The grant is scoped to "
    "this one bucket and cannot reach the lake."
)

DEFAULT_CERT = (
    "The distribution serves on its own cloudfront.net domain with the default certificate, "
    "which pins TLSv1 as the minimum protocol version and cannot be raised without a custom "
    "domain and an ACM certificate in us-east-1. There is no domain for this project. Accepted "
    "risk, revisited if a domain is ever attached."
)

# next is built with trailingSlash, so /driver/ has to resolve to /driver/index.html
REWRITE = """
function handler(event) {
  var request = event.request;
  var uri = request.uri;
  if (uri.endsWith('/')) {
    request.uri = uri + 'index.html';
  } else if (!uri.includes('.')) {
    request.uri = uri + '/index.html';
  }
  return request;
}
"""


class WebStack(Stack):
    def __init__(
        self,
        scope: Construct,
        construct_id: str,
        *,
        env_name: str,
        **kwargs: Any,
    ) -> None:
        super().__init__(scope, construct_id, **kwargs)
        Tags.of(self).add("component", "web")

        # the whole site is rebuilt by `pnpm build`, so nothing here is worth retaining.
        # emptied by hand before a destroy rather than by an auto-delete lambda: one custom
        # resource and one never-expiring log group is a worse trade than a line in the runbook
        self.bucket = s3.Bucket(
            self,
            "SiteBucket",
            bucket_name=f"pit-advisor-web-{env_name}-{self.account}",
            block_public_access=s3.BlockPublicAccess.BLOCK_ALL,
            encryption=s3.BucketEncryption.S3_MANAGED,
            enforce_ssl=True,
            removal_policy=RemovalPolicy.DESTROY,
        )

        rewrite = cloudfront.Function(
            self,
            "DirectoryIndex",
            code=cloudfront.FunctionCode.from_inline(REWRITE),
            runtime=cloudfront.FunctionRuntime.JS_2_0,
            comment="append index.html to directory requests",
        )

        headers = cloudfront.ResponseHeadersPolicy(
            self,
            "SecurityHeaders",
            security_headers_behavior=cloudfront.ResponseSecurityHeadersBehavior(
                content_type_options=cloudfront.ResponseHeadersContentTypeOptions(override=True),
                frame_options=cloudfront.ResponseHeadersFrameOptions(
                    frame_option=cloudfront.HeadersFrameOption.DENY, override=True
                ),
                referrer_policy=cloudfront.ResponseHeadersReferrerPolicy(
                    referrer_policy=cloudfront.HeadersReferrerPolicy.SAME_ORIGIN, override=True
                ),
                strict_transport_security=cloudfront.ResponseHeadersStrictTransportSecurity(
                    access_control_max_age=Duration.days(365),
                    include_subdomains=True,
                    override=True,
                ),
                content_security_policy=cloudfront.ResponseHeadersContentSecurityPolicy(
                    # next's hydration bootstrap is an inline script and a static export has no
                    # server to mint a nonce, so script-src has to allow inline. the page renders
                    # no user input and takes no query parameter, so there is nothing to inject
                    content_security_policy=(
                        "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src "
                        "'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; "
                        "connect-src 'self'; object-src 'none'; frame-ancestors 'none'; "
                        "base-uri 'none'"
                    ),
                    override=True,
                ),
            ),
        )

        self.distribution = cloudfront.Distribution(
            self,
            "Distribution",
            comment=f"pit advisor dashboard ({env_name})",
            default_root_object="index.html",
            # singapore is in 200 and not in 100, and the reader is in singapore
            price_class=cloudfront.PriceClass.PRICE_CLASS_200,
            default_behavior=cloudfront.BehaviorOptions(
                origin=origins.S3BucketOrigin.with_origin_access_control(self.bucket),
                viewer_protocol_policy=cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
                allowed_methods=cloudfront.AllowedMethods.ALLOW_GET_HEAD,
                cache_policy=cloudfront.CachePolicy.CACHING_OPTIMIZED,
                response_headers_policy=headers,
                compress=True,
                function_associations=[
                    cloudfront.FunctionAssociation(
                        function=rewrite,
                        event_type=cloudfront.FunctionEventType.VIEWER_REQUEST,
                    )
                ],
            ),
            error_responses=[
                cloudfront.ErrorResponse(
                    http_status=403,
                    response_http_status=404,
                    response_page_path="/404.html",
                    ttl=Duration.minutes(5),
                ),
                cloudfront.ErrorResponse(
                    http_status=404,
                    response_http_status=404,
                    response_page_path="/404.html",
                    ttl=Duration.minutes(5),
                ),
            ],
        )

        Validations.of(self.bucket).acknowledge(
            Acknowledgment(id="AwsSolutions-S1", reason=NO_ACCESS_LOGS)
        )
        for finding, reason in (
            ("AwsSolutions-CFR1", NO_WAF),
            ("AwsSolutions-CFR2", NO_WAF),
            ("AwsSolutions-CFR3", NO_ACCESS_LOGS),
            ("AwsSolutions-CFR4", DEFAULT_CERT),
            ("AwsSolutions-CFR5", DEFAULT_CERT),
            ("AwsSolutions-CFR7", NO_WAF),
        ):
            Validations.of(self.distribution).acknowledge(Acknowledgment(id=finding, reason=reason))

        dev_user = iam.User.from_user_name(
            self,
            "DevUser",
            self.node.try_get_context("devUserName") or "pitadvisor-dev",
        )
        publish = iam.ManagedPolicy(
            self,
            "DevWebAccess",
            managed_policy_name=f"pitadvisor-web-publish-{env_name}",
            users=[dev_user],
            statements=[
                iam.PolicyStatement(
                    actions=["s3:ListBucket", "s3:GetBucketLocation"],
                    resources=[self.bucket.bucket_arn],
                ),
                iam.PolicyStatement(
                    # the export is a tree of generated filenames, so the sync needs the bucket
                    actions=["s3:GetObject", "s3:PutObject", "s3:DeleteObject"],
                    resources=[self.bucket.arn_for_objects("*")],
                ),
                iam.PolicyStatement(
                    actions=["cloudfront:CreateInvalidation", "cloudfront:GetInvalidation"],
                    resources=[
                        self.format_arn(
                            service="cloudfront",
                            region="",
                            resource="distribution",
                            resource_name=self.distribution.distribution_id,
                        )
                    ],
                ),
                iam.PolicyStatement(
                    actions=["cloudformation:DescribeStacks"],
                    resources=[self.stack_id],
                ),
            ],
        )

        Validations.of(publish).acknowledge(
            Acknowledgment(
                id="AwsSolutions-IAM5[Resource::<SiteBucket397A1860.Arn>/*]",
                reason=SITE_WILDCARD,
            )
        )

        self._publisher(env_name)

        CfnOutput(self, "SiteBucketName", value=self.bucket.bucket_name)
        CfnOutput(self, "DistributionId", value=self.distribution.distribution_id)
        CfnOutput(self, "SiteUrl", value=f"https://{self.distribution.distribution_domain_name}")

    def _publisher(self, env_name: str) -> None:
        """The role GitHub Actions assumes to publish. No static key exists anywhere."""
        repo = self.node.try_get_context("githubRepo") or PLACEHOLDER_REPO
        # github is rolling out immutable subject claims, which put the numeric owner and repo
        # ids in the sub: repo:owner@1234/name@5678:ref:refs/heads/main. the plain form is what
        # every guide still shows and what the docs describe, so both are trusted and nothing
        # else is. read the repo's own prefix from
        # /repos/{owner}/{repo}/actions/oidc/customization/sub and pass it as githubSubjectPrefix
        prefix = self.node.try_get_context("githubSubjectPrefix")
        subjects = [f"repo:{repo}:ref:refs/heads/main"]
        if prefix and f"{prefix}:ref:refs/heads/main" not in subjects:
            subjects.append(f"{prefix}:ref:refs/heads/main")

        # the account is shared, so a provider for this issuer may already exist. creating a
        # second one for the same url fails, which is why the arn can be passed in instead.
        # this is the L1 on purpose: the L2 ships a custom resource to fetch the thumbprint,
        # which means a lambda and a log group nobody set a retention on
        existing = self.node.try_get_context("githubOidcProviderArn")
        provider_arn = (
            existing
            or iam.CfnOIDCProvider(
                self,
                "GithubOidc",
                url="https://token.actions.githubusercontent.com",
                client_id_list=["sts.amazonaws.com"],
                # IAM validates this issuer against its own trusted CAs and ignores the thumbprint,
                # but CloudFormation still wants the property
                thumbprint_list=["6938fd4d98bab03faadb97b34396831e3780aea1"],
            ).attr_arn
        )

        role = iam.Role(
            self,
            "PublishRole",
            role_name=f"pitadvisor-web-publish-{env_name}",
            description="assumed by github actions to publish the dashboard",
            max_session_duration=Duration.hours(1),
            managed_policies=[
                iam.ManagedPolicy.from_managed_policy_name(
                    self, "ViewsRead", f"pitadvisor-views-read-{env_name}"
                )
            ],
            assumed_by=iam.WebIdentityPrincipal(
                provider_arn,
                {
                    "StringEquals": {
                        "token.actions.githubusercontent.com:aud": "sts.amazonaws.com",
                        # the branch is part of the boundary: a pull request from a fork
                        # carries a different sub and cannot assume this role
                        # a list under StringEquals is an or, so this is still an allowlist
                        "token.actions.githubusercontent.com:sub": subjects,
                    }
                },
            ),
        )
        role.add_to_policy(
            iam.PolicyStatement(
                actions=["s3:ListBucket", "s3:GetBucketLocation"],
                resources=[self.bucket.bucket_arn],
            )
        )
        role.add_to_policy(
            iam.PolicyStatement(
                actions=["s3:GetObject", "s3:PutObject", "s3:DeleteObject"],
                resources=[self.bucket.arn_for_objects("*")],
            )
        )
        role.add_to_policy(
            iam.PolicyStatement(
                # so the workflow can read the distribution id off the stack rather than
                # carrying a second repository variable that can drift from the deployment
                actions=["cloudformation:DescribeStacks"],
                resources=[self.stack_id],
            )
        )
        role.add_to_policy(
            iam.PolicyStatement(
                actions=["cloudfront:CreateInvalidation", "cloudfront:GetInvalidation"],
                resources=[
                    self.format_arn(
                        service="cloudfront",
                        region="",
                        resource="distribution",
                        resource_name=self.distribution.distribution_id,
                    )
                ],
            )
        )

        Validations.of(role).acknowledge(
            Acknowledgment(
                id="AwsSolutions-IAM5[Resource::<SiteBucket397A1860.Arn>/*]", reason=CI_WILDCARD
            )
        )

        CfnOutput(self, "PublishRoleArn", value=role.role_arn)
        CfnOutput(self, "PublishRoleRepo", value=repo)
